[project]
name = "simulation-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "channel-code-lib2",
]

# use for sync with git 
#[tool.uv.sources]
#channel-code-lib2 = { git = "ssh://git@gitlab.kit.edu/kit/cel/projects/cc/channel-code-lib2",
#    branch = "ensemble_diverity"}

[tool.uv.sources]
channel-code-lib2 = { path = "../channel-code-lib2", editable = true }